#!/bin/bash
#$ -l h_rt=0:30:00  # max runtime
#$ -l virtual_free=25M # max memory use, excluding shared libs, toolserver
#$ -l h_vmem=256M # max memory use, including shared libs, Tools Labs
#$ -l arch=* # mag op zowel linux als solaris
#$ -N tvpupdater-valhallasw # naam van taak, eindigt in naam eigenaar
#$ -M valhallasw@arctus.nl
#$ -m a # alleen mails bij een abort (vanwege bv. runtime-overschrijding)
#$ -b y # draai over netwerkschijf ipv het bestand te kopiëren
#$ -o /dev/null # output naar /dev/null
#$ -e $HOME/log/tvpupdater-valhallasw.err
#$ -q task

cd ~/bots/tvpupdater
./runbot $@
echo $? > $HOME/RETVAL
